CREATE TABLE CS_AUDIOMETRI
(
  MCU_NO    VARCHAR2(20 BYTE)                   NOT NULL,
  EMPID     VARCHAR2(10 BYTE)                   NOT NULL,
  PERIODE   VARCHAR2(4 BYTE),
  MCU_DATE  DATE,
  PAKET     VARCHAR2(50 BYTE),
  KN250     NUMBER,
  KN500     NUMBER,
  KN1000    NUMBER,
  KN2000    NUMBER,
  KN3000    NUMBER,
  KN4000    NUMBER,
  KN6000    NUMBER,
  KN8000    NUMBER,
  KR250     NUMBER,
  KR500     NUMBER,
  KR1000    NUMBER,
  KR2000    NUMBER,
  KR3000    NUMBER,
  KR4000    NUMBER,
  KR6000    NUMBER,
  KR8000    NUMBER,
  KESAN_KN  VARCHAR2(250 BYTE),
  KESAN_KR  VARCHAR2(250 BYTE),
  KESIMP    VARCHAR2(500 BYTE),
  INS_DATE  DATE,
  INS_EMP   VARCHAR2(10 BYTE),
  UPD_DATE  DATE,
  UPD_EMP   VARCHAR2(10 BYTE)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_AUDIOMETRI_IDX_01 ON CS_AUDIOMETRI
(MCU_NO, EMPID, PERIODE, MCU_DATE)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;