CREATE TABLE CS_ADD_INFO
(
  INFO_CD      VARCHAR2(10 BYTE)                NOT NULL,
  POLI_CD      VARCHAR2(10 BYTE)                NOT NULL,
  DESCRIPTION  VARCHAR2(50 BYTE),
  INS_DATE     DATE,
  STATUS       VARCHAR2(1 BYTE)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;