CREATE TABLE CS_ANAMNESA
(
  ANAMNESA_ID        NUMBER                     NOT NULL,
  RM_NO              VARCHAR2(20 BYTE)          NOT NULL,
  INSP_DATE          DATE                       NOT NULL,
  BLOOD_PRESS        VARCHAR2(10 BYTE),
  PULSE              VARCHAR2(10 BYTE),
  TEMPERATURE        VARCHAR2(10 BYTE),
  ALLERGY            VARCHAR2(100 BYTE),
  ANAMNESA           VARCHAR2(300 BYTE),
  DISEASE_NOW        VARCHAR2(300 BYTE),
  DISEASE_THEN       VARCHAR2(300 BYTE),
  DISEASE_FAMILY     VARCHAR2(300 BYTE),
  ANAMNESA_PHYSICAL  VARCHAR2(300 BYTE),
  ANAMNESA_OTHER     VARCHAR2(250 BYTE),
  BB                 VARCHAR2(10 BYTE),
  TB                 VARCHAR2(10 BYTE),
  INS_DATE           DATE,
  INS_EMP            VARCHAR2(10 BYTE),
  VISIT_NO           VARCHAR2(10 BYTE),
  UPD_DATE           DATE,
  UPD_EMP            VARCHAR2(10 BYTE),
  INFO_K             VARCHAR2(10 BYTE),
  INFOP1             VARCHAR2(20 BYTE),
  INFOP2             VARCHAR2(20 BYTE),
  INFOP3             VARCHAR2(20 BYTE),
  INFOP4             VARCHAR2(20 BYTE),
  INFOP5             VARCHAR2(20 BYTE)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_ANAMNESA_IDX_01 ON CS_ANAMNESA
(ANAMNESA_ID, RM_NO, INSP_DATE, VISIT_NO, INFO_K)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;