CREATE TABLE CS_BIRTH_CERTIFICATE
(
  CER_ID      NUMBER                            NOT NULL,
  RM_NO       VARCHAR2(20 BYTE)                 NOT NULL,
  INSP_DATE   DATE                              NOT NULL,
  VISIT_NO    VARCHAR2(10 BYTE),
  LETTER_DT   DATE,
  LETTER_NO   VARCHAR2(50 BYTE),
  BIRTH_WEEK  VARCHAR2(10 BYTE),
  BIRTH_DATE  DATE,
  CNT_LEAVE   VARCHAR2(10 BYTE),
  BGN_DATE    DATE,
  END_DATE    DATE,
  BGN_WORK    DATE,
  CER_TYPE    VARCHAR2(1 BYTE),
  INS_DATE    DATE,
  INS_EMP     VARCHAR2(10 BYTE),
  UPD_DATE    DATE,
  UPD_EMP     VARCHAR2(10 BYTE)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_BIRTH_CERTI_IDX_01 ON CS_BIRTH_CERTIFICATE
(CER_ID, RM_NO, INSP_DATE, VISIT_NO, LETTER_DT, 
LETTER_NO, CER_TYPE)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;