CREATE TABLE CS_CALL_LOG
(
  CALL_ID   NUMBER,
  QUE       VARCHAR2(5 BYTE),
  TYPE_INS  VARCHAR2(5 BYTE),
  STAT      VARCHAR2(30 BYTE),
  PARAM     VARCHAR2(200 BYTE),
  FLAG      VARCHAR2(1 BYTE),
  INS_EMP   VARCHAR2(10 BYTE),
  INS_DATE  DATE
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;