CREATE TABLE CS_DIAGNOSA_ITEM
(
  ITEM_CD    VARCHAR2(10 BYTE)                  NOT NULL,
  ITEM_NAME  VARCHAR2(250 BYTE)                 NOT NULL,
  STATUS     VARCHAR2(1 BYTE),
  INS_DATE   DATE,
  INS_EMP    VARCHAR2(10 BYTE),
  CAT_ID     VARCHAR2(10 BYTE)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_DIAG_ITEM_IDX_01 ON CS_DIAGNOSA_ITEM
(ITEM_CD, STATUS, CAT_ID)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE CS_DIAGNOSA_ITEM ADD (
  CONSTRAINT CS_DIAGNOSA_ITEM_U01
 UNIQUE (ITEM_CD));