CREATE TABLE CS_EMPLOYEES
(
  EMPID        VARCHAR2(20 CHAR)                NOT NULL,
  RFID         VARCHAR2(30 CHAR),
  NAME         VARCHAR2(150 CHAR),
  DEPT         VARCHAR2(50 CHAR),
  LINE         VARCHAR2(200 CHAR),
  POSITION     VARCHAR2(50 CHAR),
  MANAGER      VARCHAR2(150 CHAR),
  BIRTH_PLACE  VARCHAR2(50 BYTE),
  BIRTH_DATE   VARCHAR2(10 BYTE),
  AGE          NUMBER,
  GENDER       VARCHAR2(20 BYTE),
  ADDRESS      VARCHAR2(500 CHAR),
  BLOOD_TYPE   VARCHAR2(10 CHAR),
  HEIGHT       NUMBER,
  WEIGHT       NUMBER,
  RETIRE_DT    DATE,
  INS_DATE     DATE,
  INS_EMP      VARCHAR2(10 CHAR),
  DEPTCD       VARCHAR2(10 CHAR)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_EMPLOYEES_IDX_01 ON CS_EMPLOYEES
(EMPID, RFID, NAME, POSITION)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;