CREATE TABLE CS_MEDICINE_STOK
(
  PERIOD       VARCHAR2(10 BYTE),
  MED_CD       VARCHAR2(10 BYTE),
  STOCK        NUMBER,
  EXPIRE_DATE  DATE,
  INS_DATE     DATE,
  INS_EMP      VARCHAR2(10 BYTE),
  UPD_DATE     DATE,
  UPD_EMP      VARCHAR2(10 BYTE)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_MEDICINE_STOK_IDX_01 ON CS_MEDICINE_STOK
(PERIOD, MED_CD, STOCK, EXPIRE_DATE)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;