CREATE TABLE CS_POLICLINIC
(
  POLI_CD     VARCHAR2(10 BYTE)                 NOT NULL,
  POLI_NAME   VARCHAR2(50 BYTE)                 NOT NULL,
  POLI_GROUP  VARCHAR2(10 BYTE),
  POLI_PIC    VARCHAR2(3 BYTE),
  STATUS      VARCHAR2(3 BYTE),
  INS_DATE    DATE
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_POLICLINIC_IDX_01 ON CS_POLICLINIC
(POLI_CD, POLI_GROUP, POLI_PIC, STATUS)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;