CREATE TABLE CS_RECEIPT
(
  RECEIPT_ID  NUMBER                            NOT NULL,
  RM_NO       VARCHAR2(20 BYTE)                 NOT NULL,
  INSP_DATE   DATE                              NOT NULL,
  MED_CD      VARCHAR2(10 BYTE),
  FORMULA     VARCHAR2(10 BYTE),
  MED_QTY     NUMBER,
  MED_REMARK  VARCHAR2(300 BYTE),
  INS_DATE    DATE,
  INS_EMP     VARCHAR2(10 BYTE),
  UPD_DATE    DATE,
  UPD_EMP     VARCHAR2(10 BYTE),
  VISIT_NO    VARCHAR2(10 BYTE),
  TYPE_DRINK  VARCHAR2(10 BYTE),
  CONFIRM     VARCHAR2(1 BYTE)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_RECEIPT_IDX_01 ON CS_RECEIPT
(RECEIPT_ID, RM_NO, INSP_DATE, MED_CD, MED_QTY, 
VISIT_NO, CONFIRM)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;