CREATE TABLE CS_REFER
(
  REFER_ID   NUMBER                             NOT NULL,
  RM_NO      VARCHAR2(20 BYTE)                  NOT NULL,
  INSP_DATE  DATE                               NOT NULL,
  LETTER_DT  DATE,
  HOS_NAME   VARCHAR2(50 BYTE),
  HOS_DOC    VARCHAR2(50 BYTE),
  LETTER_NO  VARCHAR2(50 BYTE),
  INS_DATE   DATE,
  INS_EMP    VARCHAR2(10 BYTE),
  VISIT_NO   VARCHAR2(10 BYTE),
  UPD_DATE   DATE,
  UPD_EMP    VARCHAR2(10 BYTE)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_REFER_IDX_01 ON CS_REFER
(REFER_ID, RM_NO, INSP_DATE, LETTER_DT, VISIT_NO)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;