CREATE TABLE CS_SICK_LETER
(
  LETTER_ID       NUMBER                        NOT NULL,
  RM_NO           VARCHAR2(20 BYTE)             NOT NULL,
  INSP_DATE       DATE                          NOT NULL,
  PRINT_YN        VARCHAR2(1 BYTE),
  VISIT_NO        VARCHAR2(10 BYTE),
  LETTER_DT       DATE,
  LETTER_NO       VARCHAR2(50 BYTE),
  RETURN_WORK     VARCHAR2(1 BYTE),
  CONTROL         DATE,
  BGN_REST        DATE,
  END_REST        DATE,
  CNT_REST        VARCHAR2(10 BYTE),
  BGN_LIMIT       DATE,
  END_LIMIT       DATE,
  CNT_LIMIT       VARCHAR2(10 BYTE),
  LIMIT01         VARCHAR2(10 BYTE),
  LIMIT02         VARCHAR2(10 BYTE),
  LIMIT03         VARCHAR2(10 BYTE),
  LIMIT04         VARCHAR2(10 BYTE),
  LIMIT05         VARCHAR2(10 BYTE),
  LIMIT06         VARCHAR2(10 BYTE),
  LIMIT07         VARCHAR2(10 BYTE),
  LIMIT08         VARCHAR2(10 BYTE),
  LIMIT09         VARCHAR2(10 BYTE),
  LIMIT10         VARCHAR2(10 BYTE),
  REMARK          VARCHAR2(100 BYTE),
  INS_DATE        DATE,
  INS_EMP         VARCHAR2(10 BYTE),
  UPD_DATE        DATE,
  UPD_EMP         VARCHAR2(10 BYTE),
  REMARK_MACHINE  VARCHAR2(50 BYTE)
)
TABLESPACE TS_ITASSET_DATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX CS_SICK_LETER_IDX_01 ON CS_SICK_LETER
(LETTER_ID, RM_NO, INSP_DATE, VISIT_NO, LETTER_DT, 
LETTER_NO)
LOGGING
TABLESPACE TS_ITASSET_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       2147483645
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;